script:
  - mkdir -p generated
  - echo "OMG HELLO WORLD" > generated/index.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: generated
