language: python
python:
  - '3.5'
script:
  - cp mkdocs.yml ..
  - pip install mkdocs
  - mkdir -p /tmp/generated
  - mkdocs -d /tmp/generated -f ../mkdocs.yml build
  - mv /tmp/generated .

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: generated
