language: python
python:
  - '3.5'
script:
  - pip install mkdocs
  - mkdir -p generated
  - mkdocs build -d generated
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: generated
