language: python
python:
  - '3.5'
script:
  - pip install mkdocs
  - mkdir -p /tmp/generated
  - mkdocs build -d /tmp/generated
  - mv /tmp/generated .
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: generated
